"""empty message

Revision ID: 109cee790c85
Revises: c6f3e4297088
Create Date: 2022-12-13 12:37:14.307062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109cee790c85'
down_revision = 'c6f3e4297088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('pick_location', sa.String(length=20), nullable=False),
    sa.Column('drop_location', sa.String(length=20), nullable=False),
    sa.Column('vehicle', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
