"""empty message

Revision ID: 2758b193c230
Revises: 9d8a9c589377
Create Date: 2022-11-21 16:55:03.093944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2758b193c230'
down_revision = '9d8a9c589377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('courier_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('id')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=20), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('email')
        batch_op.drop_column('service_id')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('courier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('courier_id')

    # ### end Alembic commands ###
