"""empty message

Revision ID: 8066debe77a3
Revises: 
Create Date: 2022-11-21 12:07:09.746428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8066debe77a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('vehicle', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=20), nullable=False),
    sa.Column('photo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('deliverer')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('deliverer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('services')
    # ### end Alembic commands ###
