"""empty message

Revision ID: c3d7d60a3277
Revises: 2758b193c230
Create Date: 2022-11-21 17:14:11.277839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d7d60a3277'
down_revision = '2758b193c230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_courier')
    with op.batch_alter_table('courier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('courier_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('id')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=20), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('email')
        batch_op.drop_column('service_id')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('courier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('courier_id')

    op.create_table('_alembic_tmp_courier',
    sa.Column('firstname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=20), nullable=False),
    sa.Column('courier_id', sa.INTEGER(), nullable=False)
    )
    # ### end Alembic commands ###
