"""Changed primary keys to id

Revision ID: c6f3e4297088
Revises: e2fbd8fd7a30
Create Date: 2022-11-21 17:28:25.655403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f3e4297088'
down_revision = 'e2fbd8fd7a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_courier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_courier',
    sa.Column('firstname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=20), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False)
    )
    # ### end Alembic commands ###
