"""empty message

Revision ID: d44ccbd3617f
Revises: 109cee790c85
Create Date: 2022-12-13 13:13:00.930822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44ccbd3617f'
down_revision = '109cee790c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
